server:
  port: 8080

spring:
  output:
    ansi:
      enabled: always

  profiles:
    active: dev

  datasource:
    url: jdbc:h2:./db_dev;MODE=MySQL
    username: root
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 100

logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.orm.jdbc.bind: trace
    org.hibernate.orm.jdbc.extract: trace
    org.springframework.transaction.interceptor: trace
